  steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/smartcube-api-stg:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/smartcube-api-stg:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'smartcube-api-stg'
    - '--image'
    - 'gcr.io/$PROJECT_ID/smartcube-api-stg:$COMMIT_SHA'
    - '--set-env-vars' 
    - 'APP_PORT=8080'
    - '--set-env-vars' 
    - 'DB_HOST=10.8.176.4'
    - '--set-env-vars' 
    - 'DB_PORT=3306'
    - '--set-env-vars' 
    - 'DB_USER=root'
    - '--set-env-vars' 
    - 'DB_PASS='
    - '--set-env-vars' 
    - 'DB_NAME=smartcube_db'
    - '--set-env-vars' 
    - 'DB_DIALECT=mysql'
    - '--region'
    - 'asia-east1'
    - '--platform' 
    - 'managed'
    - '--allow-unauthenticated'
  images:
  - 'gcr.io/$PROJECT_ID/smartcube-api-stg:$COMMIT_SHA'
